install.packages("boot")
install.packages("car")
install.packages("QuantPsyc")
install.packages("lmtest")
install.packages("sandwich")
install.packages("vars")
install.packages("nortest")
install.packages("MASS")
library(boot) 
library(car)
library(QuantPsyc)
library(lmtest)
library(sandwich)
library(vars)
library(nortest)
library(MASS)


setwd("C:\\finder\\work\\IvyR\\project")
data <- read.csv("C:\\finder\\work\\IvyR\\project\\Insurance_Marketing-Customer-Value-Analysis.csv")
head(data)
str(data)
boxplot(data$Customer.Lifetime.Value )
quantile(data$Customer.Lifetime.Value,c(0,0.05,0.1,0.25,0.5,0.75,0.90,0.95,0.99,0.995,1))
data2<- data[data$Customer.Lifetime.Value<=41788,]
boxplot(data2$Customer.Lifetime.Value)
quantile(data2$Customer.Lifetime.Value, c(0,0.05,0.1,0.25,0.5,0.75,0.90,0.95,0.96,0.97,0.98,0.991,0.992,0.993,0.994,0.995,0.996,0.997,0.998,0.999,1))
data3<-data[data$Customer.Lifetime.Value<=15115, ]
boxplot(data3$Customer.Lifetime.Value)
sapply(data3, function(x) sum(is.na(x)))
nrow(data)
nrow(data3)
data<-data3
nrow(data)
names(data)
fit<- lm(Customer.Lifetime.Value ~ I("Response=NO") + Coverage + I("Education=EducationCollege")+ I("Education=EducationHigh School or Below ") + Effective.To.Date + EmploymentStatus + Gender + Location.Code + Marital.Status + Policy.Type + Policy + Renew.Offer.Type + Sales.Channel + Vehicle.Class + Vehicle.Size, data=data)
summary(fit)
